import * as ts from "typescript";
import { logger } from "../utils/logger";

const BLACKLISTED_IMPORTS = [
    "fs",
    "fs/promises",
    "child_process",
    "net",
    "http",
    "https",
    "os",
    "path",
    "crypto",
    "cluster",
    "dgram",
    "repl",
    "tls",
    "axios",
    "node-fetch",
    "ws"
];

// Dangerous native globals that should not be invoked natively
const BLACKLISTED_CALLS = [
    "eval",
    "fetch",
    "setTimeout",
    "setInterval",
    "exec",
    "Function"
];

/**
 * Validates a generated code string using TypeScript's Abstract Syntax Tree (AST).
 * 
 * Expert-level isolation: We do not just run the code and hope for the best.
 * We compile the string into syntax nodes and deeply spider the tree to physically
 * prevent the LLM from attempting prompt-injections to hijack loopback boundaries.
 * 
 * @param sourceCode The raw TypeScript code string generated by the Coder
 * @returns boolean True if safe, throws Error if dangerous
 */
export function validateCodeSafetyAST(sourceCode: string): boolean {
    // 1. Create a virtual AST representation of the unexecuted string
    const sourceFile = ts.createSourceFile(
        "sandboxedFile.ts",
        sourceCode,
        ts.ScriptTarget.Latest,
        true // setParentNodes
    );

    let isSafe = true;
    let detectedViolation = "";

    // 2. Spider the Syntax Tree
    const walkTree = (node: ts.Node) => {
        // Rule A: Intercept any `import` or `require` declarations
        if (ts.isImportDeclaration(node)) {
            const moduleSpecifier = node.moduleSpecifier;
            if (ts.isStringLiteral(moduleSpecifier)) {
                const target = moduleSpecifier.text.toLowerCase();
                if (BLACKLISTED_IMPORTS.includes(target)) {
                    isSafe = false;
                    detectedViolation = `FATAL: Unauthorized Import Blocked -> '${target}'`;
                    return;
                }
            }
        }

        // Rule B: Intercept Call Expressions (functions like 'require(x)' or 'eval(x)')
        if (ts.isCallExpression(node)) {
            if (ts.isIdentifier(node.expression)) {
                const fnName = node.expression.text;

                // Block dynamic require()
                if (fnName === "require" && node.arguments.length > 0) {
                    const arg0 = node.arguments[0];
                    if (ts.isStringLiteral(arg0)) {
                        if (BLACKLISTED_IMPORTS.includes(arg0.text.toLowerCase())) {
                            isSafe = false;
                            detectedViolation = `FATAL: Dynamic require() of blocked module -> '${arg0.text}'`;
                            return;
                        }
                    } else {
                        // Blanket ban dynamic requires with variables entirely since we can't AST track string concatenation
                        isSafe = false;
                        detectedViolation = `FATAL: Dynamic variable require() is strictly prohibited.`;
                        return;
                    }
                }

                // Block dangerous globals
                if (BLACKLISTED_CALLS.includes(fnName)) {
                    isSafe = false;
                    detectedViolation = `FATAL: Dangerous Global Call Detected -> '${fnName}'`;
                    return;
                }
            }
        }

        // Recursively crawl children if we haven't failed yet
        if (isSafe) {
            ts.forEachChild(node, walkTree);
        }
    };

    walkTree(sourceFile);

    if (!isSafe) {
        logger.warn("sandbox_violation_caught", { reason: detectedViolation });
        throw new Error(`AstSandboxError: Code rejected for safety violations. ${detectedViolation}`);
    }

    return true;
}
