export enum BuyerState {
    INIT = 'INIT',
    OFFER_SENT = 'OFFER_SENT',
    WAITING_SELLER = 'WAITING_SELLER',
    SELLER_AGREED = 'SELLER_AGREED',
    FINAL_CONFIRM_SENT = 'FINAL_CONFIRM_SENT',
    WAIT_ESCROW = 'WAIT_ESCROW',
    DEPOSIT_SENT = 'DEPOSIT_SENT',
    WAIT_DELIVERY = 'WAIT_DELIVERY',
    FUNDS_RELEASED = 'FUNDS_RELEASED',
    COMPLETED = 'COMPLETED'
}

export enum SellerState {
    INIT = 'INIT',
    WAIT_OFFER = 'WAIT_OFFER',
    OFFER_RECEIVED = 'OFFER_RECEIVED',
    AGREED = 'AGREED',
    WAIT_FINAL_CONFIRM = 'WAIT_FINAL_CONFIRM',
    WAIT_ESCROW = 'WAIT_ESCROW',
    DEPOSIT_SENT = 'DEPOSIT_SENT',
    WAIT_DELIVERY = 'WAIT_DELIVERY',
    FUNDS_RELEASED = 'FUNDS_RELEASED',
    COMPLETED = 'COMPLETED'
}
