import { Connection, PublicKey, Keypair, Transaction, VersionedTransaction } from "@solana/web3.js";
import { AnchorProvider, Wallet } from "@coral-xyz/anchor";
import { logger } from "../utils/logger";

/**
 * Builds an AnchorProvider from a Connection and Keypair.
 * The provider is required to interact with the on-chain program.
 */
function buildProvider(
  connection: Connection,
  keypair: Keypair
): AnchorProvider {
  const wallet: Wallet = {
    publicKey: keypair.publicKey,
    signTransaction: async <T extends Transaction | VersionedTransaction>(tx: T): Promise<T> => {
      if (tx instanceof Transaction) {
        tx.partialSign(keypair);
      }
      return tx;
    },
    signAllTransactions: async <T extends Transaction | VersionedTransaction>(txs: T[]): Promise<T[]> => {
      txs.forEach((tx) => {
        if (tx instanceof Transaction) {
          tx.partialSign(keypair);
        }
      });
      return txs;
    },
    payer: keypair,
  } as unknown as Wallet;

  return new AnchorProvider(connection, wallet, {
    commitment: "confirmed",
    preflightCommitment: "confirmed",
  });
}

/**
 * Loads the escrow program.
 *
 * In production, you would fetch the IDL from chain or load from a JSON file.
 * For now we create a minimal program reference that can be used to derive
 * PDAs and send raw transactions. Once the IDL is generated by `anchor build`,
 * replace the placeholder with the real IDL import.
 */
export async function loadProgram(
  connection: Connection,
  keypair: Keypair,
  programIdStr: string
): Promise<{ provider: AnchorProvider; programId: PublicKey }> {
  try {
    const programId = new PublicKey(programIdStr);
    const provider = buildProvider(connection, keypair);

    // Verify the program account exists on-chain
    const accountInfo = await connection.getAccountInfo(programId);
    if (!accountInfo) {
      logger.error("program_not_found", { programId: programIdStr });
    } else {
      logger.info("program_account_verified", {
        programId: programIdStr,
        executable: accountInfo.executable,
        owner: accountInfo.owner.toBase58(),
        dataLength: accountInfo.data.length,
      });
    }

    logger.info("program_loaded", { programId: programIdStr });

    return { provider, programId };
  } catch (error) {
    logger.error("program_load_failed", {}, error);
    throw error;
  }
}

/**
 * Derives the Deal PDA address for a given buyer and deal ID.
 */
export function deriveDealPda(
  programId: PublicKey,
  buyer: PublicKey,
  dealId: bigint
): [PublicKey, number] {
  const dealIdBuffer = Buffer.alloc(8);
  dealIdBuffer.writeBigUInt64LE(dealId);

  return PublicKey.findProgramAddressSync(
    [Buffer.from("deal"), buyer.toBuffer(), dealIdBuffer],
    programId
  );
}

/**
 * Derives the Config PDA address.
 */
export function deriveConfigPda(
  programId: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("config")],
    programId
  );
}
